name: build
on:
  push: {tags: ["v*"]}
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.13"}
      - run: pip install ".[build]"
      - run: python build.py
      - uses: actions/upload-artifact@v4
        with:
          name: ETLStudio-${{ matrix.os }}
          path: dist/
